// server/admin-ui/src/components/ToastProvider.tsx
import { AlertTriangle, CheckCircle, Info, XCircle } from 'lucide-react'
import { createPortal } from 'react-dom'
import { useToastStore } from '../hooks/useToast'

export default function ToastProvider() {
  const toasts = useToastStore((s) => s.toasts)

  const iconMap = {
    success: <CheckCircle size={16} />,
    error: <XCircle size={16} />,
    warning: <AlertTriangle size={16} />,
    info: <Info size={16} />,
  }

  const colorClasses = {
    success: 'border-l-success text-success',
    error: 'border-l-destructive text-destructive',
    warning: 'border-l-warning text-warning',
    info: 'border-l-info text-info',
  }

  return createPortal(
    <div className="pointer-events-none fixed right-4 top-4 z-[9999] flex max-w-sm flex-col gap-2">
      {toasts.map((t) => (
        <div
          key={t.id}
          className={`flex items-center gap-2 rounded-lg border border-border bg-card px-4 py-2.5 shadow-md border-l-[3px] text-sm leading-relaxed ${colorClasses[t.type]}`}
          style={{ animation: 'toast-in 250ms ease-out' }}
        >
          <span className="flex shrink-0">{iconMap[t.type]}</span>
          <span className="text-foreground">{t.message}</span>
        </div>
      ))}
    </div>,
    document.body
  )
}

// server/admin-ui/src/components/ToastProvider.vue
<template>
  <Teleport to="body">
    <TransitionGroup name="toast" tag="div" class="toast-container">
      <div
        v-for="t in toasts"
        :key="t.id"
        class="toast-item"
        :class="'toast-' + t.type"
      >
        <div class="toast-icon">
          <CheckCircle v-if="t.type === 'success'" :size="16" />
          <XCircle v-else-if="t.type === 'error'" :size="16" />
          <AlertTriangle v-else-if="t.type === 'warning'" :size="16" />
          <Info v-else :size="16" />
        </div>
        <span class="toast-msg">{{ t.message }}</span>
      </div>
    </TransitionGroup>
  </Teleport>
</template>

<script setup lang="ts">
import { AlertTriangle, CheckCircle, Info, XCircle } from 'lucide-vue-next';
import { useToast } from '../composables/useToast';

const { toasts } = useToast();
</script>

<style scoped>
.toast-container {
  position: fixed;
  top: 16px;
  right: 16px;
  z-index: 9999;
  display: flex;
  flex-direction: column;
  gap: 8px;
  pointer-events: none;
  max-width: 360px;
}

.toast-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 10px 16px;
  border-radius: var(--radius-md);
  background: var(--bg-surface);
  box-shadow: var(--shadow-md);
  font-size: 13px;
  line-height: 1.4;
  pointer-events: auto;
  border: 1px solid var(--border);
  transition: all var(--transition-normal);
}
.toast-icon {
  flex-shrink: 0;
  display: flex;
}

.toast-success { border-left: 3px solid var(--success); }
.toast-success .toast-icon { color: var(--success); }
.toast-error   { border-left: 3px solid var(--error); }
.toast-error .toast-icon   { color: var(--error); }
.toast-warning { border-left: 3px solid var(--warning); }
.toast-warning .toast-icon { color: var(--warning); }
.toast-info    { border-left: 3px solid var(--info); }
.toast-info .toast-icon    { color: var(--info); }

/* ─── Transition ─── */
.toast-enter-active { transition: all 250ms ease-out; }
.toast-leave-active { transition: all 200ms ease-in; }
.toast-enter-from { opacity: 0; transform: translateX(40px); }
.toast-leave-to   { opacity: 0; transform: translateX(40px); }

@media (max-width: 480px) {
  .toast-container { left: 8px; right: 8px; top: 8px; max-width: none; }
  .toast-item { padding: 10px 12px; font-size: 12px; }
}
</style>
