// server/admin-ui/src/views/Dashboard.tsx
import { Activity, Bot, FileText, Image, Loader, MessageSquare, Server, User as UserIcon } from 'lucide-react'
import { useCallback, useEffect, useRef, useState } from 'react'
import { adminApi, api, type ActivityEntry, type ActivityResponse, type StatsSummary } from '../api'
import AIConfigPanel from '../components/AIConfigPanel'
import BotManager from '../components/BotManager'
import { useToast } from '../hooks/useToast'
import { useAuthStore } from '../stores/authStore'

interface KpiCardDef {
  label: string
  color: string
  Icon: React.FC<{ size?: number }>
}

interface HealthResponse {
  uptime: string
  storageType: string
  storageUsedFormatted: string
  dbSizeFormatted: string
}

const animationCache = new Map<string, number>()

const kpiDefs: KpiCardDef[] = [
  { label: 'Memo', color: '#7C3AED', Icon: FileText },
  { label: '日记', color: '#F97316', Icon: MessageSquare },
  { label: '资源', color: '#10B981', Icon: Image },
  { label: 'Bot', color: '#3B82F6', Icon: Bot },
]

const actionLabels: Record<string, string> = {
  create_memo: '创建 Memo', update_memo: '更新 Memo', delete_memo: '删除 Memo',
  create_diary: '创建日记', update_diary: '更新日记', delete_diary: '删除日记',
  create_bot: '创建 Bot', update_bot: '更新 Bot', delete_bot: '删除 Bot',
  login: '登录', change_password: '修改密码',
}

function fmtTime(ts: number) {
  const d = new Date(ts)
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`
}

function easeOutCubic(t: number) {
  return 1 - Math.pow(1 - t, 3)
}

function useAnimatedValue(target: number, key: string) {
  const [current, setCurrent] = useState(() => animationCache.get(key) ?? 0)
  const currentRef = useRef(current)
  const rafRef = useRef(0)

  useEffect(() => {
    currentRef.current = current
  }, [current])

  useEffect(() => {
    const start = currentRef.current
    const startTime = performance.now()
    const duration = 600

    function step(now: number) {
      const p = Math.min((now - startTime) / duration, 1)
      const v = Math.round(start + (target - start) * easeOutCubic(p))
      setCurrent(v)
      animationCache.set(key, v)
      if (p < 1) rafRef.current = requestAnimationFrame(step)
    }
    rafRef.current = requestAnimationFrame(step)
    return () => cancelAnimationFrame(rafRef.current)
  }, [key, target])

  return current
}

const tagColors: Record<string, string> = {
  info: 'bg-info/10 text-info',
  warn: 'bg-warning/10 text-warning',
  error: 'bg-destructive/10 text-destructive',
}

export default function Dashboard() {
  const auth = useAuthStore()
  const toast = useToast()

  const [kpiValues, setKpiValues] = useState([0, 0, 0, 0])
  const [activityEntries, setActivityEntries] = useState<ActivityEntry[]>([])
  const [activityLoading, setActivityLoading] = useState(false)
  const [health, setHealth] = useState<HealthResponse | null>(null)

  const [pwdForm, setPwdForm] = useState({ oldPassword: '', newPassword: '' })
  const [pwdSaving, setPwdSaving] = useState(false)

  const loadStats = useCallback(async () => {
    try {
      const data = (await adminApi('/stats')) as StatsSummary
      setKpiValues([data.memos.total, data.diaries.total, data.resources.total, data.bots.total])
    } catch {
      /* ignore */
    }
  }, [])

  const loadActivity = useCallback(async () => {
    setActivityLoading(true)
    try {
      const data = (await adminApi('/activity', { params: { limit: 20 } })) as ActivityResponse
      setActivityEntries(data.entries || [])
    } catch {
      setActivityEntries([])
    } finally {
      setActivityLoading(false)
    }
  }, [])

  const loadHealth = useCallback(async () => {
    try {
      setHealth((await adminApi('/health')) as HealthResponse)
    } catch {
      /* ignore */
    }
  }, [])

  useEffect(() => {
    void (async () => {
      await Promise.all([loadStats(), loadActivity(), loadHealth()])
    })()
  }, [loadStats, loadActivity, loadHealth])

  async function changePwd(e: React.FormEvent) {
    e.preventDefault()
    if (!pwdForm.oldPassword || !pwdForm.newPassword) {
      toast.error('请填写完整')
      return
    }
    setPwdSaving(true)
    try {
      await api('/auth/change-password', { method: 'POST', body: pwdForm })
      toast.success('密码已修改')
      setPwdForm({ oldPassword: '', newPassword: '' })
    } catch {
      toast.error('修改失败，请检查当前密码')
    } finally {
      setPwdSaving(false)
    }
  }

  return (
    <div className="mx-auto max-w-[1200px]">
      <div className="mb-4 grid grid-cols-2 gap-2.5 sm:mb-5 sm:gap-3 lg:grid-cols-4">
        {kpiDefs.map((def, i) => (
          <KpiCard key={def.label} def={def} value={kpiValues[i]} />
        ))}
      </div>

      <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
        <div className="rounded-lg border border-border bg-card">
          <div className="flex items-center justify-between border-b border-border px-4 py-3">
            <h3 className="flex items-center gap-1.5 text-[13px] font-semibold text-foreground">
              <Activity size={16} />
              最近活动
            </h3>
            <button className="border-none bg-transparent text-xs text-muted-foreground cursor-pointer hover:text-foreground transition-colors" onClick={loadActivity}>刷新</button>
          </div>
          <div className="max-h-[340px] overflow-y-auto px-4 py-3">
            {activityLoading && <div className="skeleton h-[120px]" />}
            {!activityLoading && !activityEntries.length && <div className="py-8 text-center text-sm text-muted-foreground">暂无活动记录</div>}
            {!activityLoading && activityEntries.length > 0 && (
              <div className="flex flex-col gap-px">
                {activityEntries.map((e, i) => (
                  <div key={`${e.timestamp}-${e.action}-${i}`} className="flex flex-wrap items-center gap-1.5 rounded-md px-2 py-[7px] text-xs transition-colors hover:bg-muted sm:gap-2">
                    <span className="font-mono text-[11px] text-muted-foreground shrink-0 sm:w-[58px]">{fmtTime(e.timestamp)}</span>
                    <span className={`rounded px-1.5 py-px text-[10px] font-semibold uppercase shrink-0 ${tagColors[e.level] || tagColors.info}`}>{e.level}</span>
                    <span className="font-medium text-foreground shrink-0">{actionLabels[e.action] || e.action}</span>
                    <span className="basis-full text-muted-foreground sm:basis-auto sm:min-w-0 sm:overflow-hidden sm:text-ellipsis sm:whitespace-nowrap">{e.detail}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        <BotManager />

        <div className="rounded-lg border border-border bg-card">
          <div className="flex items-center justify-between border-b border-border px-4 py-3">
            <h3 className="flex items-center gap-1.5 text-[13px] font-semibold text-foreground">
              <UserIcon size={16} />
              账号
            </h3>
          </div>
          <div className="px-4 py-3">
            <div className="flex items-center justify-between py-0.5 text-[13px]">
              <span className="text-[11px] text-muted-foreground">用户</span>
              <span className="font-medium text-foreground">{auth.user?.username || '-'}</span>
            </div>
            <hr className="my-2.5 border-t border-border" />
            <form onSubmit={changePwd} className="flex flex-col gap-2">
              <div className="flex flex-col gap-1.5 sm:flex-row">
                <input
                  type="password"
                  className="h-7 rounded-md border border-border bg-muted px-2 text-xs text-foreground font-sans outline-none transition-colors focus:border-ring flex-1"
                  placeholder="当前密码"
                  value={pwdForm.oldPassword}
                  onChange={(e) => setPwdForm({ ...pwdForm, oldPassword: e.target.value })}
                />
                <input
                  type="password"
                  className="h-7 rounded-md border border-border bg-muted px-2 text-xs text-foreground font-sans outline-none transition-colors focus:border-ring flex-1"
                  placeholder="新密码"
                  value={pwdForm.newPassword}
                  onChange={(e) => setPwdForm({ ...pwdForm, newPassword: e.target.value })}
                />
              </div>
              <button type="submit" className="inline-flex items-center justify-center gap-1.5 rounded-md bg-primary px-3 py-1.5 text-xs font-medium text-primary-foreground transition-colors hover:bg-primary/80 disabled:opacity-50" disabled={pwdSaving}>
                {pwdSaving ? <Loader size={13} className="spin" /> : <span>修改密码</span>}
              </button>
            </form>
          </div>
        </div>

        <div className="rounded-lg border border-border bg-card">
          <div className="flex items-center justify-between border-b border-border px-4 py-3">
            <h3 className="flex items-center gap-1.5 text-[13px] font-semibold text-foreground">
              <Server size={16} />
              系统状态
            </h3>
            <button className="border-none bg-transparent text-xs text-muted-foreground cursor-pointer hover:text-foreground transition-colors" onClick={loadHealth}>刷新</button>
          </div>
          <div className="px-4 py-3">
            {!health ? <div className="py-8 text-center text-sm text-muted-foreground">加载中...</div> : (
              <div className="grid grid-cols-1 gap-2.5 sm:grid-cols-2">
                <HealthItem label="运行时间" value={health.uptime} />
                <HealthItem label="存储类型" value={health.storageType} />
                <HealthItem label="存储用量" value={health.storageUsedFormatted} />
                <HealthItem label="数据库" value={health.dbSizeFormatted} />
              </div>
            )}
          </div>
        </div>
      </div>

      <div className="mt-3">
        <AIConfigPanel />
      </div>
    </div>
  )
}

function KpiCard({ def, value }: { def: KpiCardDef; value: number }) {
  const animated = useAnimatedValue(value, def.label)
  return (
    <div className="flex items-center gap-2.5 rounded-lg bg-card px-3 py-3.5 shadow-sm transition-shadow hover:shadow-md sm:gap-3.5 sm:px-4 sm:py-[18px]">
      <div className="flex size-9 shrink-0 items-center justify-center rounded-md sm:size-[42px]" style={{ background: `color-mix(in srgb, ${def.color} 12%, transparent)`, color: def.color }}>
        <def.Icon size={18} />
      </div>
      <div className="flex min-w-0 flex-col">
        <span className="font-mono text-xl font-bold text-foreground leading-tight tabular-nums sm:text-2xl">{animated}</span>
        <span className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">{def.label}</span>
      </div>
    </div>
  )
}

function HealthItem({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex flex-col gap-0.5">
      <span className="text-[11px] text-muted-foreground">{label}</span>
      <span className="font-mono text-xs font-semibold text-foreground">{value}</span>
    </div>
  )
}

// server/admin-ui/src/views/Dashboard.vue
<template>
  <div class="dashboard">
    <!-- KPI Cards -->
    <div class="kpi-grid">
      <div v-for="c in kpiCards" :key="c.label" class="kpi-card">
        <div class="kpi-icon" :style="{ '--kpi-color': c.color }">
          <component :is="c.iconComp" :size="20" />
        </div>
        <div class="kpi-body">
          <span class="kpi-value">{{ animatedValues[c.label] ?? 0 }}</span>
          <span class="kpi-label">{{ c.label }}</span>
        </div>
      </div>
    </div>

    <!-- Main Grid -->
    <div class="main-grid">
      <!-- Activity -->
      <section class="panel">
        <div class="panel-header">
          <h3><Activity :size="16" /> 最近活动</h3>
          <button class="btn-ghost" @click="loadActivity">刷新</button>
        </div>
        <div class="panel-body panel-body--scroll">
          <div v-if="activityLoading" class="skeleton skeleton-line" style="height: 120px" />
          <div v-else-if="!activityEntries.length" class="empty">暂无活动记录</div>
          <div v-else class="activity-list">
            <div v-for="e in activityEntries" :key="e.timestamp + e.action" class="activity-row">
              <span class="act-time">{{ fmtTime(e.timestamp) }}</span>
              <span class="act-tag" :class="'tag-' + e.level">{{ e.level }}</span>
              <span class="act-action">{{ actionLabels[e.action] || e.action }}</span>
              <span class="act-detail">{{ e.detail }}</span>
            </div>
          </div>
        </div>
      </section>

      <!-- Bots (extracted component) -->
      <BotManager />

      <!-- Profile -->
      <section class="panel">
        <div class="panel-header">
          <h3><UserIcon :size="16" /> 账号</h3>
        </div>
        <div class="panel-body">
          <div class="profile-row">
            <span class="label">用户</span>
            <span class="value">{{ auth.user?.username || '-' }}</span>
          </div>
          <hr class="divider" />
          <form class="pwd-form" @submit.prevent="changePwd">
            <div class="input-group">
              <input v-model="pwdForm.oldPassword" type="password" class="input-sm" placeholder="当前密码" />
              <input v-model="pwdForm.newPassword" type="password" class="input-sm" placeholder="新密码" />
            </div>
            <button type="submit" class="btn-sm" :disabled="pwdSaving">
              <Loader v-if="pwdSaving" :size="13" class="spin" />
              <span v-else>修改密码</span>
            </button>
          </form>
        </div>
      </section>

      <!-- Health -->
      <section class="panel">
        <div class="panel-header">
          <h3><Server :size="16" /> 系统状态</h3>
          <button class="btn-ghost" @click="loadHealth">刷新</button>
        </div>
        <div class="panel-body">
          <div v-if="!health" class="empty">加载中...</div>
          <div v-else class="health-grid">
            <div class="health-item">
              <span class="label">运行时间</span>
              <span class="value-mono">{{ health.uptime }}</span>
            </div>
            <div class="health-item">
              <span class="label">存储类型</span>
              <span class="value-mono">{{ health.storageType }}</span>
            </div>
            <div class="health-item">
              <span class="label">存储用量</span>
              <span class="value-mono">{{ health.storageUsedFormatted }}</span>
            </div>
            <div class="health-item">
              <span class="label">数据库</span>
              <span class="value-mono">{{ health.dbSizeFormatted }}</span>
            </div>
          </div>
        </div>
      </section>
    </div>

    <!-- AI Config (extracted component) -->
    <div class="section-gap">
      <AIConfigPanel />
    </div>
  </div>
</template>

<script setup lang="ts">
import { Activity, Bot, FileText, Image, Loader, MessageSquare, Server, User as UserIcon } from 'lucide-vue-next';
import { onMounted, reactive, ref } from 'vue';
import { adminApi, api } from '../api';
import AIConfigPanel from '../components/AIConfigPanel.vue';
import BotManager from '../components/BotManager.vue';
import { useToast } from '../composables/useToast';
import { useAuthStore } from '../stores/auth';

const auth = useAuthStore();
const toast = useToast();

/* ─── KPI ─── */
const kpiCards = ref([
  { label: 'Memo', value: 0, color: '#7C3AED', iconComp: FileText },
  { label: '日记', value: 0, color: '#F97316', iconComp: MessageSquare },
  { label: '资源', value: 0, color: '#10B981', iconComp: Image },
  { label: 'Bot', value: 0, color: '#3B82F6', iconComp: Bot },
]);

const animatedValues = reactive<Record<string, number>>({});

function animateValue(target: number, key: string) {
  const start = animatedValues[key] ?? 0;
  const duration = 600;
  const startTime = performance.now();
  function step(now: number) {
    const elapsed = now - startTime;
    const p = Math.min(elapsed / duration, 1);
    animatedValues[key] = Math.round(start + (target - start) * easeOutCubic(p));
    if (p < 1) requestAnimationFrame(step);
  }
  requestAnimationFrame(step);
}
function easeOutCubic(t: number) { return 1 - Math.pow(1 - t, 3); }

async function loadStats() {
  try {
    const data: any = await adminApi('/stats');
    kpiCards.value[0].value = data.memos.total;
    kpiCards.value[1].value = data.diaries.total;
    kpiCards.value[2].value = data.resources.total;
    kpiCards.value[3].value = data.bots.total;
    kpiCards.value.forEach(c => animateValue(c.value, c.label));
  } catch { /* ignore */ }
}

/* ─── Activity ─── */
const activityEntries = ref<any[]>([]);
const activityLoading = ref(false);
const actionLabels: Record<string, string> = {
  create_memo: '创建 Memo', update_memo: '更新 Memo', delete_memo: '删除 Memo',
  create_diary: '创建日记', update_diary: '更新日记', delete_diary: '删除日记',
  create_bot: '创建 Bot', update_bot: '更新 Bot', delete_bot: '删除 Bot',
  login: '登录', change_password: '修改密码',
};

async function loadActivity() {
  activityLoading.value = true;
  try {
    const data: any = await adminApi('/activity', { params: { limit: 20 } });
    activityEntries.value = data.entries || [];
  } catch { activityEntries.value = []; }
  finally { activityLoading.value = false; }
}

function fmtTime(ts: number) {
  const d = new Date(ts);
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

/* ─── Password ─── */
const pwdForm = reactive({ oldPassword: '', newPassword: '' });
const pwdSaving = ref(false);

async function changePwd() {
  if (!pwdForm.oldPassword || !pwdForm.newPassword) { toast.error('请填写完整'); return; }
  pwdSaving.value = true;
  try {
    await api('/auth/change-password', { method: 'POST', body: pwdForm });
    toast.success('密码已修改');
    pwdForm.oldPassword = '';
    pwdForm.newPassword = '';
  } catch { toast.error('修改失败，请检查当前密码'); }
  finally { pwdSaving.value = false; }
}

/* ─── Health ─── */
const health = ref<any>(null);
async function loadHealth() {
  try { health.value = await adminApi('/health'); } catch { /* ignore */ }
}

onMounted(() => Promise.all([loadStats(), loadActivity(), loadHealth()]));
</script>

<style scoped>
.dashboard { max-width: 1200px; margin: 0 auto; }
.section-gap { margin-top: 12px; }

/* ═══ KPI Grid ═══ */
.kpi-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 12px;
  margin-bottom: 20px;
}
.kpi-card {
  background: var(--bg-surface);
  border-radius: var(--radius-md);
  padding: 18px 16px;
  display: flex;
  align-items: center;
  gap: 14px;
  box-shadow: var(--shadow-sm);
  transition: box-shadow var(--transition-fast), transform var(--transition-fast);
}
.kpi-card:hover { box-shadow: var(--shadow-md); transform: translateY(-1px); }
.kpi-icon {
  width: 42px; height: 42px; border-radius: var(--radius-sm);
  display: flex; align-items: center; justify-content: center;
  background: color-mix(in srgb, var(--kpi-color) 12%, transparent);
  color: var(--kpi-color); flex-shrink: 0;
}
.kpi-body { display: flex; flex-direction: column; min-width: 0; }
.kpi-value {
  font-size: 24px; font-weight: 700; font-family: var(--font-mono);
  color: var(--text-primary); line-height: 1.1; font-variant-numeric: tabular-nums;
}
.kpi-label {
  font-size: 11px; color: var(--text-tertiary);
  text-transform: uppercase; letter-spacing: 0.5px; font-weight: 500;
}

/* ═══ Main Grid ═══ */
.main-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }

/* ═══ Panel ═══ */
.panel {
  background: var(--bg-surface); border-radius: var(--radius-md);
  box-shadow: var(--shadow-sm); overflow: hidden;
  display: flex; flex-direction: column;
}
.panel-header {
  display: flex; align-items: center; justify-content: space-between;
  padding: 14px 16px 0;
}
.panel-header h3 {
  font-size: 14px; font-weight: 600; color: var(--text-primary);
  display: flex; align-items: center; gap: 8px;
}
.panel-body { padding: 12px 16px 16px; }
.panel-body--scroll { max-height: 340px; overflow-y: auto; }

/* ═══ Activity ═══ */
.activity-list { display: flex; flex-direction: column; gap: 1px; }
.activity-row {
  display: flex; align-items: center; gap: 8px;
  padding: 7px 8px; border-radius: var(--radius-sm);
  font-size: 12px; transition: background var(--transition-fast);
}
.activity-row:hover { background: var(--bg-hover); }
.act-time {
  font-family: var(--font-mono); font-size: 11px;
  color: var(--text-tertiary); flex-shrink: 0; width: 58px;
}
.act-tag {
  font-size: 10px; font-weight: 600; padding: 1px 5px;
  border-radius: 3px; text-transform: uppercase; flex-shrink: 0;
}
.tag-info  { background: var(--info-soft); color: var(--info); }
.tag-warn  { background: var(--warning-soft); color: var(--warning); }
.tag-error { background: var(--error-soft); color: var(--error); }
.act-action { font-weight: 500; flex-shrink: 0; color: var(--text-primary); }
.act-detail {
  color: var(--text-secondary); overflow: hidden;
  text-overflow: ellipsis; white-space: nowrap; min-width: 0;
}

/* ═══ Profile ═══ */
.profile-row { display: flex; align-items: center; justify-content: space-between; font-size: 13px; padding: 2px 0; }
.divider { border: none; border-top: 1px solid var(--border); margin: 10px 0; }
.pwd-form { display: flex; flex-direction: column; gap: 8px; }
.input-group { display: flex; gap: 6px; }

/* ═══ Health ═══ */
.health-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
.health-item { display: flex; flex-direction: column; gap: 2px; }
.label { font-size: 11px; color: var(--text-tertiary); }
.value { font-size: 13px; font-weight: 500; color: var(--text-primary); }
.value-mono { font-family: var(--font-mono); font-size: 12px; font-weight: 600; color: var(--text-primary); }

/* ═══ Shared primitives ═══ */
.btn-ghost {
  display: inline-flex; align-items: center; gap: 4px;
  padding: 4px 10px; border: none; background: transparent;
  color: var(--text-secondary); font-size: 12px; font-family: var(--font-sans);
  cursor: pointer; border-radius: var(--radius-sm);
  transition: all var(--transition-fast);
}
.btn-ghost:hover { background: var(--bg-hover); color: var(--text-primary); }

.btn-sm {
  display: inline-flex; align-items: center; justify-content: center; gap: 6px;
  padding: 6px 14px; border: none; border-radius: var(--radius-sm);
  background: var(--accent); color: var(--on-accent);
  font-size: 12px; font-weight: 600; font-family: var(--font-sans);
  cursor: pointer; transition: all var(--transition-fast);
}
.btn-sm:hover:not(:disabled) { background: var(--accent-hover); }
.btn-sm:disabled { opacity: 0.5; cursor: not-allowed; }

.input-sm {
  border: 1.5px solid var(--border); border-radius: var(--radius-sm);
  background: var(--bg-page); color: var(--text-primary);
  font-family: var(--font-sans); outline: none;
  padding: 6px 10px; font-size: 12px; flex: 1;
  transition: all var(--transition-fast);
}
.input-sm:focus { border-color: var(--accent); background: var(--bg-surface); }
.input-sm::placeholder { color: var(--text-tertiary); }

.empty { text-align: center; padding: 20px; color: var(--text-tertiary); font-size: 13px; }
.skeleton, .skeleton-line { animation: skeleton-pulse 1.5s ease-in-out infinite; border-radius: var(--radius-sm); }
.skeleton { background: var(--bg-surface-alt); }
.skeleton-line { background: var(--bg-hover); }
.spin { animation: spin 1s linear infinite; }
@keyframes spin { to { transform: rotate(360deg); } }

/* ═══ Responsive ═══ */
@media (max-width: 1024px) {
  .kpi-grid { grid-template-columns: repeat(2, 1fr); }
}
@media (max-width: 768px) {
  .kpi-grid { gap: 8px; margin-bottom: 14px; }
  .kpi-card { padding: 14px 12px; gap: 10px; }
  .kpi-icon { width: 36px; height: 36px; }
  .kpi-value { font-size: 20px; }
  .main-grid { grid-template-columns: 1fr; gap: 10px; }
  .panel-header { padding: 12px 12px 0; }
  .panel-body { padding: 10px 12px 14px; }
  .act-time { width: auto; font-size: 10px; }
  .activity-row { flex-wrap: wrap; gap: 4px; padding: 6px; }
  .act-action { font-size: 11px; width: 100%; }
  .act-detail { width: 100%; font-size: 11px; }
}
@media (max-width: 480px) {
  .kpi-grid { gap: 6px; }
  .kpi-card { padding: 10px; gap: 8px; }
  .kpi-icon { width: 32px; height: 32px; }
  .kpi-value { font-size: 17px; }
  .kpi-label { font-size: 10px; }
  .act-time { display: none; }
  .act-tag { font-size: 9px; padding: 1px 4px; }
  .health-grid { grid-template-columns: 1fr; }
  .input-group { flex-direction: column; }
  .panel-header h3 { font-size: 13px; }
}
</style>
